services:
  - type: web
    name: emparo-periperi
    env: node
    plan: starter
    region: oregon
    buildCommand: "npm install && npm install vite@^5.4.14 camelcase-css && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_DATABASE_URL
        value: libsql://emparo-periperi-flash.aws-eu-west-1.turso.io
      - key: TURSO_AUTH_TOKEN
        value: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NTA2OTg2ODcsImlkIjoiNGNiZGQ0MjctZmY2NS00YzZkLTlkY2QtNGMwYTEwODkzNTUwIiwicmlkIjoiNDYzOGQ5OTQtM2IzNS00NGQ3LWI3MTYtNTExYWMwZmRmMWYzIn0.2-O_tm8rGQIlKfN_xVhYXdGJlemapdyrysEJXm89Hr2BZJT5PUSdrUngFzhVLwi3IkV9C84oeQmHuX8xMOVGBw